######  JP/ac/osaka_u/ender/util/Makefile:	
#	created to compile the regex package
# 	

PACKAGE=JP.ac.osaka_u.ender.util
TOPDIR=../../../../..

PACKAGES = \
	regex

include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make
