<!-- This file is meant to be included. -*-html-helper-*- -->
<!-- formatting ideas stolen from: 				   -->
<!-- 	http://barley.electriclichen.com/~dmarti/linuxmanship.html -->
<table border=0 width="100%" align=center cellspacing=0 cellpadding=5>
  <tr> <th colspan=2 bgcolor="#c40026"> &nbsp;
       <th align=center> Documentation Overview
  <tr> <th colspan=2 bgcolor="#c40026"> &nbsp;
       <td colspan=2 bgcolor=silver>&nbsp;

  <tr>  <td width=20>&nbsp;
    <th align=right valign=top bgcolor=silver>Release 2.0:
    <td>
	<a href="/PIA/README">README</a>,
        &nbsp;<a href="/PIA/Doc/Release">/Release&nbsp;notes/</a>, 
        &nbsp;<a href="/PIA/Doc/FAQ/">/FAQs/</a>
    </td><td bgcolor=silver>&nbsp; 
  <tr>	 <td>&nbsp; 
    <th align=right valign=top bgcolor=silver>Getting Started:
    <td>
	<a href="/PIA/Doc/intro.html">Introduction</a>
    </td><td bgcolor=silver>&nbsp; 
  <tr>	 <td>&nbsp;
    <th align=right valign=top bgcolor=silver>Introductions:
    <td>
	<a href="http://www.RiSource.org/">The PIA group</a>
    </td> <td bgcolor=silver>&nbsp; 
  <tr>	 <td>&nbsp;
    <th align=right valign=top bgcolor=silver>
	<a href="/PIA/Doc/Manuals/">Manuals:</a>
    <td>
	<a href="/PIA/Doc/doclist.html">Documentation List</a>
    </td> <td bgcolor=silver>&nbsp; 
  <tr>	 <td>&nbsp;
    <th align=right valign=top bgcolor=silver>
	<a href="/PIA/Doc">Other Docs:</a>
    <td><a href="/PIA/Doc/Notes/">/Notes/</a> 
    </td> <td bgcolor=silver>&nbsp; 
  <if><test match='crc.ricoh.com'>&url;><then>
  <tr>	 <td>&nbsp;
    <!-- This row only appears inside Ricoh.  Should be an include -->
    <th align=right valign=top bgcolor=silver>Demonstrations:
    <td>
	<a href="/PIA/Doc/demos.html">Appliances</a>, 
        &nbsp;<a href="http://ookami.crc.ricoh.com:8888/MB3/home.if">MediaBoard</a>,
	&nbsp;<a href="http://Forms:8000/">Form&nbsp;server</a>,
	&nbsp;<a href="http://gelion:8888/">Steve's&nbsp;pia</a>
    </td> <td bgcolor=silver>&nbsp; 
  </tr>
  </if>
  <tr> <td>&nbsp; <td bgcolor=silver colspan=3>&nbsp;
</table>
<inc-footer cvsid="doc-grid.inc,v 1.2 1999/03/03 17:43:30 pgage Exp">
