<!-- This file is meant to be included. -*-html-helper-*- -->
<!-- formatting ideas stolen from: 				   -->
<!-- 	http://barley.electriclichen.com/~dmarti/linuxmanship.html -->
<table border=0 width="100%" align=center cellspacing=0 cellpadding=5>
  <tr> <th colspan=2 bgcolor="#c40026"> &nbsp;
       <th align=center> Documentation Overview
  <tr> <th colspan=2 bgcolor="#c40026"> &nbsp;
       <td colspan=2 bgcolor=silver>&nbsp;

  <tr>  <td width=20>&nbsp;
    <th align=right valign=top bgcolor=silver>
	<a href="/Doc/Release/">Release Notes:</a> </th>
    <td>
	||&nbsp;<a href="/Doc/Release/r2.0.html"><strong>2.0</strong></a> 
	||&nbsp;<a href="/PIA/README">README</a>
        ||&nbsp;<a href="/Doc/Release">/Release&nbsp;notes/</a> 
        ||&nbsp;<a href="/Doc/FAQ/">/FAQs/</a>
    </td>
    <td bgcolor=silver>&nbsp; 
  <tr>	 <td>&nbsp;
    <th align=right valign=top bgcolor=silver>
	<a href="/Doc/">Documentation:</a> </th>
    <td>
	||&nbsp;<a href="/Doc/doclist.html">Index</a> 
	||&nbsp;<a href="/Doc/intro.html">Introduction</a> 
        ||&nbsp;<a href="/Doc/Notes/">/Notes/</a> 
	||&nbsp;<a href="/Doc/">/directory/</a>
    </td>
    <td bgcolor=silver>&nbsp; 
  <tr>	 <td>&nbsp; 
    <th align=right valign=top bgcolor=silver>Links: </th>
    <td>
	||&nbsp;<a href="http://www.RiSource.org/">[www.RiSource.org]</a>
	(&nbsp;<a href="http://www.RiSource.org/PIA">/PIA</a> )
	||&nbsp;<a href="http://pia.rsv.ricoh.com/">[pia.rsv.ricoh.com]</a>
    </td>
    <td bgcolor=silver>&nbsp; 
  <tr> <td>&nbsp; <td bgcolor=silver colspan=3>&nbsp;
</table>
<inc-footer cvsid="$Id: doc-grid.inc,v 1.9 1999-05-11 01:28:17 steve Exp $">
