<!-- This file is included in the root home page for public servers -->
<h3>Welcome to the PIA group's public web site.</h3>

 See the documentation links below for descriptions of what  PIA stands for
 (Platforms for Information Appliances), what a personal information agency
 is, what paper fro information agency is, and why you should care.

<p>
Casual browsers will be most interested in the <a
href="&PIA:url;/Doc/demos.html">Demos</a>.

<hr>
<p>	The PIA group announces the initial alpha release of the "Personal
	Information Agency", a proxy web server that enables a
	new way of using the web.  Sun and Linux users can begin using the
	PIA immediately by executing the command below:

<p> <code><strong>pia</strong></code>

<p><b>Caution</b>: 
	This release still contains some rough edges and is intended for 
	experimental use.  Constructive criticisms is greatly appreciated.
	Report bugs to the PIA group.

<!-- $Id: public-welcome.inc,v 1.5 2000-04-18 19:00:10 steve Exp $ -->
