<!-- This file is included in the root home page for personal PIA's -->
<h3>Welcome to the PIA</h3>

<p> This is the home page of your personal PIA.  It is running as a process
    under your own user name, and is accessible through the URL
&lt;<a href="http://&piaHOST;:&piaPORT;/">http://&piaHOST;:&piaPORT;/</a>&gt;.
    Of course, if you're looking at this page in a web browser, you already
    know that.

<p> You can find out more about this <em>particular</em> PIA server from the
    <a href="/Admin">Admin</a> agent, which is used to perform server
    management functions.  You can find out about its implementation from the
    <a href="/PIA/Doc/Manuals/Api/index.html">API</a> (Application Programming
    Interface) Manual, and by directly studying the <a
    href="/PIA/src/java/org/risource">source code</a>, all of which is online.

<p> You can find out more about the PIA framework and its role in information
    applications from the online documentation described in the table below,
    and from the PIA Developer's Website at <a
    href="http://pia.rsv.ricoh.com"><code>pia.rsv.ricoh.com</code></a>.  You
    can obtain updates and additional open-source software from <a
    href="http://www.RiSource.org/"><code>www.RiSource.org</code></a>.

<p>
<!-- $Id: welcome.inc,v 1.3 1999-03-15 20:01:28 pgage Exp $ -->
