<!-- This file is included in the root home page for personal PIA's -->
<h3>Welcome to the PIA</h3>

<dl>
  <dt> <b>ALERT!</b> </dt>
  <dd> Many things have changed recently!  If you've been using the PIA for a
       while it is <em>strongly</em> suggested that you look at the following
       documents: 

       <a href="/src/java/org/risource/site/about">About the Site Resource
       Package</a>,
       <a href="/src/java/org/risource/pia/about">About the PIA</a>,
       and <a href="/Doc/Notes/steve/naming">Steve's notes</a>.
       </dd>
</dl>

<p> This is the home page of your personal PIA.  It is running as a process
    under your own user name (if you're on Unix), and is accessible through
    the URL 
&lt;<a href="&PIA:url;/">&PIA:url;/</a>&gt;.
    Of course, if you're looking at this page in a web browser you already
    know that.

<p> You can find out more about this <em>particular</em> PIA server from the
    <a href="/~Admin">Admin</a> agent, which is used to perform server
    management functions.  You can find out about its implementation from the
    <a href="/Doc/API/internals.html">API</a> (Application Programming
    Interface) Manual, and by directly studying the <a
    href="/src/java/org/risource">source code</a>, all of which is online.

<p> You can find out more about the PIA framework and its role in information
    applications from the online documentation described in the table below,
    and from the PIA Developer's Website at <a
    href="http://www.RiSource.org/PIA"><code>/www.RiSource.org/PIA</code></a>.
    You can obtain updates and additional open-source software from <a
    href="http://www.RiSource.org/"><code>www.RiSource.org</code></a>.
    You can find a running PIA  demonstration  server at <a
    href="http://pia.rsv.ricoh.com"><code>pia.rsv.ricoh.com</code></a>.
</p>
<!-- $Id: welcome.inc,v 1.14 1999-10-20 16:21:50 steve Exp $ -->
