###### JP/Makefile:	created to compile the regex package
#

PACKAGE="JP"
TOPDIR=..

### This is the packages to be built.  
###	Only the top-level directory is needed; 
###	make descends into each one recursively.

PACKAGES = \
	ac

include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make
