<!-- Read by home.xh 			 -*-html-helper-*- -->

<h2>About ``&AGENT:name;''</h2>

<p> &AGENT:name; is your personal web-browsing assistant.  It gets its name
    from the fact that it operates when the PIA is used as a <em>proxy</em>.
    &AGENT:name; is actually a sort of ``super-agent'' under which
    <em>all</em> of the agents that operate while proxying are collected.
    These include:

<dl>
  <dt> <a href="/History">History</a>
  <dd> maintains your browsing history.
  <dt> <a href="/Toolbar">Toolbar</a>
  <dd> Toolbar agents put a ``toolbar'' of links on the front of pages.
       The Toolbar agents include:
       <ul>
	 <li> <a href="/remoteTools">remoteTools</a> for remotely-located
	      pages. 
	 <li> <a href="/fileTools">fileTools</a> for local <em>non-active</em>
	      HTML files. 
       </ul>
</dl>

<p>``&AGENT:name;'' agents ``watch over your shoulder'' while you browse the
    Web. 
<p>  

<inc-footer cvsid="about.inc,v 1.1 1999/02/04 17:44:44 steve Exp">
