<!-- Read by home.xh 			 -*-html-helper-*- -->

<h2>About ``&AGENT:name;''</h2>

<p> &AGENT:name; is your personal web-browsing assistant.  It gets its name
    from the fact that it operates when the PIA is used as a <em><a
    href="using#proxy">proxy</a></em>. 
    &AGENT:name; is actually a sort of ``super-agent'' under which
    <em>all</em> of the agents that operate while proxying are collected.
    These include:
</p>

<dl>
  <dt> <a href="/~History">History</a> </dt>
  <dd> maintains your browsing history. </dd>
  <dt> <a href="/~Toolbar">Toolbar</a> </dt>
  <dd> Toolbar agents put a ``toolbar'' of links on the front of pages.
       The Toolbar agents include:
       <ul>
	 <li> <a href="/~remoteTools">remoteTools</a> for remotely-located
	      pages. </li>
	 <li> <a href="/~fileTools">fileTools</a> for local <em>non-active</em>
	      HTML files. </li>
       </ul>
  </dd>
</dl>

<p> You can find out more about proxying, and how to set up your browser, 
    <a href="using#proxy">here</a>.
</p>

<inc-footer cvsid="$Id: about.inc,v 1.5 2000-04-18 18:59:56 steve Exp $"/>
