###### org/xml/sax/Makefile:	Simple API for XML
# 	$Id: Makefile,v 1.1 2000-01-12 01:53:26 steve Exp $


PACKAGE=org.xml.sax.helpers
TOPDIR=../../../..

FILES = $(wildcard *.java)

# include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make

