### Makefile for /Samples/Browser
#	$Id: Makefile,v 1.1 2000-10-13 22:22:24 steve Exp $
# 	COPYRIGHT 2000, RiSource.org

PIADIR=../../.
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Browser
MYPATH=/Samples/Browser
include $(MF_DIR)/file.make

