### Makefile for Doc/Tagsets
#	$Id: Makefile,v 1.1 1999-03-23 17:19:35 steve Exp $	
# 	COPYRIGHT 1998, Ricoh Silicon Valley

PIADIR=../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Tagsets
MYPATH=Doc/Tagsets

SUBDIRS=demo tsdoc

include $(MF_DIR)/file.make
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make
include $(MF_DIR)/subdir.make
