###### JP/ac/Makefile:	created to compile the regex package
#

PACKAGE="JP.ac"
TOPDIR=../..

### These are the packages to be built.  
###	Only the top-level directories are needed; 
###	make descends into each one recursively.

PACKAGES = \
	osaka_u

include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make
