<h2>About the &AGENT:name; &AGENT:type;</h2> <!-- -*-html-helper-*- -->
<!-- Copyright 1997 Ricoh Silicon Valley -->

The  &AGENT:name; &AGENT:type; toolbars on top of pages that come from
<em>outside</em> the PIA. 
This is indicated by the logo (<img src="&PIA:rootPath;Icon/logo24.png" height=24
width=24>) at the front of the banner, which is a link to the PIA's home
page.  <p>

<inc-footer cvsid="$Id: about.inc,v 1.6 2000-04-18 21:33:32 steve Exp $">
