<h2>About the &AGENT:name; &AGENT:type;</h2> <!-- -*-html-helper-*- -->
<!-- Copyright 1997 Ricoh Silicon Valley -->

The  &AGENT:name; &AGENT:type; toolbars on top of pages that come from
<em>outside</em> the PIA. 
This is indicated by the logo (<img src="/Icon/logo24.gif" height=24
width=24>) at the front of the banner, which is a link to the PIA's home
page.  <p>

<inc-footer cvsid="$Id: about.inc,v 1.3 1999-03-12 19:22:41 steve Exp $">
