###### org/xml/Makefile:	XML.org
# 	$Id: Makefile,v 1.1 1999-07-12 22:44:57 steve Exp $

PACKAGE=org.xml
TOPDIR=../..

PACKAGES = \
	sax

include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make
