######  Makefile: 
#	for the Jigsaw org.w3c.util package

PACKAGE=org.w3c.util
TOPDIR=../../..

FILES = \
	ArrayDictionary.java \
	ArrayEnumeration.java \
	AsyncLRUList.java \
	IO.java \
	LRUAble.java \
	LRUList.java \
	LRUNode.java \
	SyncLRUList.java \
	TimeFormatter.java \
	ObservableProperties.java \
	PropertyMonitoring.java \
	Unix.java \
	UnixException.java \
	ThreadCache.java \
	Trace.java \
	CountOutputStream.java \
	EmptyEnumeration.java


include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make

