######  JP/ac/osaka_u/Makefile:	created to compile the regex package
# 	

PACKAGE=JP.ac.osaka_u
TOPDIR=../../..

PACKAGES = \
	ender

include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make



