<!-- This heading is meant to be included using read. -*-html-helper-*- -->
<!-- Copyright 1997 Ricoh Silicon Valley -->
The Agency agent is a sort of ``generic control panel'' for
       <if><test exact="yes" case="insens" match='pia'>&user.name;</test>
		<then>this Information Appliance</then>
		<else>your Information Agency</else>
       </if>.

You should be able to find links to all of the information you need from the
Agency's <a href="/Agency">home page</a>.  <p>

<!-- $Id: help.inc,v 1.4 2000-02-25 22:29:41 steve Exp $ -->
