<!-- This file is included in the root home page for personal PIA's -->
<h3>Steve's PIA on &PIA:host;</h3>

<table width="100%">
<tr><td width="50%" valign="top">
<ul>
  <li> <a href="http://internal/">Internal</a> (
       <a href="http://internal/~steve/home.html">Quick Reference</a> )
  </li>
  <li> <a href="http://RiSource.org/">RiSource.org</a> |
       <a href="http://blackroot/">local mirror</a> |
       <a href="/RiSource.org/">via PIA</a>
  </li>
  <li><strong>Files:</strong>
       <a href="file:///home/lsteve/">~lsteve</a> |
       <a href="file:///home/steve/">~steve</a>
  </li>
</ul>
</td>
<td width="50%" valign="top">
<ul>
  <li> This section is coming from <code>.pia</code> in my local home
       directory, <a href="file:///home/lsteve/.pia/welcome.inc">
       /home/lsteve/.pia/welcome.inc</a>.  It assumes that the PIA is running
       on <code>blackroot</code>, my desktop machine.
  </li>
</ul>
</td></tr>
</table>

<!-- $Id: welcome.inc,v 1.1 2000-04-26 16:48:38 steve Exp $ -->
