<!-- This file is included in the root home page for steve's personal PIA -->
<h3>Steve's PIA on &PIA:host;</h3>

<table width="100%">
<tr><td width="50%" valign="top">
<ul>
  <li> <a href="&PIA:url;">PIA</a> (
       <a href="&PIA:url;-">files</a> |
       <a href="&PIA:url;/frames">frames</a>
       )
  </li>
  <li> <a href="http://RiSource.org/">RiSource.org</a> |
       <a href="http://localhost/">localhost</a>
  </li>
  <li><strong>Files:</strong> <a href="file://&PIA:home;">home</a>
       <a href="file://&PIA:home/PIA/">~/PIA</a> 
  </li>
</ul>
</td>
<td width="50%" valign="top">
<ul>
  <li> This section is coming from <code>.pia</code> in my local home
       directory, <a href="file://&PIA:home;/.pia/welcome.inc">
       &PIA:home;/.pia/welcome.inc</a>.  It assumes that the PIA is running
       on  my desktop machine, <code>&PIA:host;</code>
  </li>
</ul>
</td></tr>
</table>

<!-- $Id: welcome.inc,v 1.2 2000-05-16 21:47:33 steve Exp $ -->
