### Makefile for /Apps/Woad
#	$Id: Makefile,v 1.1 2000-06-02 23:48:31 steve Exp $
# 	COPYRIGHT 2000, RiSource.org

PIADIR=../../.
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Woad
MYPATH=/Apps/Woad
include $(MF_DIR)/file.make

