### Makefile for /Apps/Woad
#	$Id: Makefile,v 1.2 2000-08-22 23:49:38 steve Exp $
# 	COPYRIGHT 2000, RiSource.org

PIADIR=../../.
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Woad
MYPATH=/Apps/Woad

SUBDIRS= Words

include $(MF_DIR)/file.make
include $(MF_DIR)/subdir.make

