<h2><font face="Helvetica, sans-serif">Woad Warrior</font> projects:</h2>

<hide>
<doc> This include file produces a wide tabular listing of all <font
      face="Helvetica, sans-serif">Woad Warrior</font> projects.  It's in a
      separate include file so that it can be used in several different
      places. 
</doc>
</hide>

<p align="center"> <red>[temporary mock-up]</red>
</p>

<table width="90%" align="center">
  <tr>
    <th align="left"> Project </th>
    <th align="left"> tree </th>
    <th align="left">
	 <table width="100%" cellspacing=0 cellpadding=0>
	   <tr><th align="left">brief description</th>
		<th align="right"><a href="ww-help#prjlist">[help]</a></th>
	   </tr>
         </table>
    </th>
  </tr>

  <tr bgcolor="white"><!-- === FAKED === -->
    <td valign="top"> <a href="/">This PIA</a> </td>
    <td valign="top"> <a href="/.Woad/">[tree]</a></td>
    <td valign="top"> Use WOAD to browse the sources for this PIA installation
    </td>
  </tr>

</table>

<!-- $Id: ww-trees.inc,v 1.1 2000-10-21 01:07:59 steve Exp $ -->
