<!doctype tagset system "tagset.dtd">
<!-- ---------------------------------------------------------------------- -->
<!-- The contents of this file are subject to the Ricoh Source Code Public  -->
<!-- License Version 1.0 (the "License"); you may not use this file except  -->
<!-- in compliance with the License.  You may obtain a copy of the License  -->
<!-- at http://www.risource.org/RPL                                         -->
<!--                                                                        -->
<!-- Software distributed under the License is distributed on an "AS IS"    -->
<!-- basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See   -->
<!-- the License for the specific language governing rights and limitations -->
<!-- under the License.                                                     -->
<!--                                                                        -->
<!-- This code was initially developed by Ricoh Silicon Valley, Inc.        -->
<!-- Portions created by Ricoh Silicon Valley, Inc. are                     -->
<!-- Copyright (C) 1995-1999.  All Rights Reserved.                         -->
<!--                                                                        -->
<!-- Contributor(s): steve@rsv.ricoh.com                                    -->
<!-- ---------------------------------------------------------------------- -->

<tagset name=tsdoc parent=HTML tagset=xhtml>

<h1>Tagset Documentation Tagset</h1>

<doc> This file contains the XML definition for a Tagset that can be used
      for formatting Tagset files.
</doc>

<doc> Tagset definition files, their syntax, and their usual representation,
      are documented in <a href="tagset.html">tagset.html</a>.
</doc>

<h2>Definition Elements</h2>

<define element=tagset>
  <doc> &lt;tagset&gt; is the top-level element.  We have to transform it into
	an &lt;html&gt; element with appropriate head and body content. 
  </doc>
  <action><html><head>
    <title>&lt;tagset &attributes:name;&gt;</title>
    </head><body><!-- AUTOMATICALLY GENERATED -- DO NOT EDIT!!! -->
      <h1>&lt;tagset <repeat list="&attributes;"> &li; </repeat>&gt;</h1>
	<blockquote>
	  <em> This documentation was automatically generated by the
	       <code>tsdoc</code> tagset. 
	  </em>
	</blockquote>
      <if>&content;<then>&content;</then></if>
    </body></html>
  </action>
</define>

<define element=define quoted>
  <action> <if>&attributes:element;
	       <then><big><a name="&attributes:element;"
		      ><strong>&lt;define</strong></a>
	             <repeat list="&attributes;"> &li; </repeat><hide>
		     <set name="VAR:current-element">&attributes:element;</set>
		     </hide><strong>&gt;</strong> </big><br/>
	       </then>
           <elsf>&attributes:attribute;
	       <then><a name="&VAR:current-element;.&attributes:attribute;"
		      ><strong>&lt;define</strong></a>
	             <repeat list="&attributes;"> &li; </repeat><hide>
		     </hide><strong>&gt;</strong> <br/>
	       </then></elsf>
           <elsf>&attributes:entity;
	       <then><a name="&attributes:entity;"
		      ><strong>&lt;define</strong></a>
	             <repeat list="&attributes;"> &li; </repeat><hide>
		     </hide><strong>&gt;</strong> <br/>
	       </then></elsf>
	   <else><strong>&lt;define</strong>
	             <repeat list="&attributes;"> &li; </repeat><hide>
		     </hide><strong>&gt;</strong> <br/>
           </else>
           </if>
	   <if>&content;
	       <then><blockquote><expand>&content;</expand></blockquote></then>
	   </if>

  </action>
  <doc> Basically we're turning the declaration itself into a sort of header,
	except that we're assuming that headers already exist, so we just
	emphasize it.
  </doc>
</define>

<define element=undefine>
  <action> (<em>(undefine <repeat list="&attributes;"> &li; </repeat>) </em>
  </action>
  <doc> Just by changing a <tag>define</tag> to <tag>undefine</tag> one can
	make it disappear from the documentation.
  </doc>
</define>

<define element=action quoted>
  <action> <p> &lt;action&gt; ... &lt;/action&gt; </p> 
  </action>
</define>

<define element=value quoted>
  <action> <p> &lt;value&gt; ... &lt;/value&gt; </p>
  </action>
</define>

<define element=doc>
  <action>  &content;  </action>
</define>

<define element=note>
  <action>
  <dl>
    <dt> <strong>Note: </strong> (&attributes;)</dt>
    <dd> <em>&content;</em></dd>
  </dl></action>
</define>

<h2>Additional Constructs:</h2>

<define element=cvs-id>
  <action><h5>&content;</h5></action>
</define>

<define element=tag>
  <action><code>&lt;&content;&gt;</code></action>
</define>


<hr>
<b>Copyright &copy; 1998 Ricoh Silicon Valley</b><br>
<b>$Id: tsdoc.ts,v 1.1 1999-12-14 18:28:33 steve Exp $</b><br>
</tagset>

