### Makefile for /Samples
#	$Id: Makefile,v 1.1 2000-10-13 22:23:28 steve Exp $
# 	COPYRIGHT 2000, RiSource.org

PIADIR=../.
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Samples
MYPATH=/Samples
include $(MF_DIR)/file.make
include $(MF_DIR)/subdir.make


