###### misc/Makefile:	Miscelaneous Java classes.
#	Makefile,v 1.2 1999/03/02 00:46:27 pgage Exp

PACKAGE="misc"
TOPDIR=..

### These are the packages to be built.  
###	Only the top-level directories are needed; 
###	make descends into each one recursively.

FILES= \
	Jcrypt.java

#include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make














