###### misc/Makefile:	Miscelaneous Java classes.
#	$Id: Makefile,v 1.3 1999-03-24 20:47:17 steve Exp $

PACKAGE=misc
TOPDIR=..

### These are the packages to be built.  
###	Only the top-level directories are needed; 
###	make descends into each one recursively.

FILES= \
	Jcrypt.java

#include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make














