#!/bin/sh
#	Display the names of files that do _not_ contain a string
#	$Id: files-not-containing,v 1.3 1999-04-21 21:49:10 steve Exp $

re=${1-copyright}

find . '(' -name '*.java' -o -name '*.html' -o -name '*.if' -o -name '*.tex' \
        -o -name '*.p[lm]' -o -name '*.inc' -o -name '*akefile' ')' -type f  \
	\! -path '*javadoc*' \! -path '*/other/*' \
    \! -exec grep -q -i "$re" {} \; -print 
