#!/bin/sh
#	Display the names of files that contain a string
#	files-containing,v 1.1 1997/08/12 22:51:49 steve Exp

re=${1-hhmts start}

find . '(' -name '*.java' -o -name '*.html' -o -name '*.xh' -o -name '*.ts' \
	-o -name '*.tex' \
        -o -name '*.p[lm]' -o -name '*.inc' -o -name '*akefile' ')' -type f  \
	\! -path '*JavaDoc*' \! -path '*/other/*' \
    -exec grep -q -i "$re" {} \; -print 
