#!/bin/sh
# Hack to fix up <!doctype...> statements.
# NOTE: This will fail if the doctype isn't all on one line.

pat='\<\![dD][oO][cC][tT][yY][^>]+\>'
doctype='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">'

find .  '(' -name '*.html' -o -name '*.xh' -o -name '*.inc' ')' -type f \
    -exec grep -q -i '<!doctype' {} \; -print \
    -exec perl -p -i -e "s@$pat@$doctype@g" {} \; 
