#!/bin/sh
# Hack to change "by Ricoh Silicon Valley" to "by Ricoh Innovations"
# $Id: fix-silicon-valley,v 1.1 2001-04-03 00:09:30 steve Exp $
# NOTE: other instances of "rsv", and of "Ricoh Silicon Valley", are being
#	done by hand -- there are a couple of places where they shouldn't 
#	be changed, and others where I decided to remove them altogether.
#
find .  '(' -name '*.java' -o -name '*.html' -o -name '*.xh' -o -name '*.ts' \
	-o -name '*.tex' -o -name '*.make' -o -name '*.cdrom'\
        -o -name '*.p[lm]' -o -name '*.inc' -o -name '*akefile' ')' -type f \
    -exec grep -q -i 'by Ricoh Silicon Valley' {} \; -print \
    -exec perl -p -i -e 's;by Ricoh Silicon Valley;by Ricoh Innovations;g' {} \; 
