#!/bin/sh
# $Id: fix-permissions,v 1.2 1999-03-12 19:23:53 steve Exp $
#
# This script fixes permissions on directories created by someone who
# did a "cvs update" with their umask set to 22.
# Note that you have to be root in order to do this.
#
# Usage:
#	cd /pia1/pia; su; fix-permissions
#	
find . -type d -exec chmod g+w {} \;
