#!/bin/sh
#	Display lines that indicate a "hole"
#	$Id: hole-report,v 1.3 1999-04-21 21:49:11 steve Exp $

re="${1-[^=]===[^=]|unimplemented|eventually}"

find . '(' -name '*.java' -o -name '*htm?' -o -name '*.if' -o -name '*.tex' \
        -o -name '*.p[lm]' -o -name '*.inc' ')' -type f  \
	\! -path '*javadoc*' \! -path '*/other/*' \
    -exec egrep -i -n -s "$re" {} xxx \; 
