#!/bin/sh
# fix TOPDIR pointers and package names after move
find . -name '*akefile' -print \
	-exec perl -p -i -e 's@TOPDIR=@TOPDIR=\.\./@' {} \; \
	-exec perl -p -i -e 's@=\"crc@=\"org.risource@' {} \; \
	-exec perl -p -i -e 's@crc/@org/risource/@' {} \; 
