#!/bin/sh
#	Recursive grep
#	$Id: rgrep,v 1.4 1999-04-21 21:49:12 steve Exp $


find . '(' -name '*.java' -o -name '*html' -o -name '*.xh' -o -name '*.ts' \
	-o -name '*.tex' -o -name '*make*' \
        -o -name '*.p[lm]' -o -name '*.inc' -o -name '*akefile' ')' -type f  \
	\! -path '*javadoc*' \
    -exec grep $* {} /dev/null \;
