#!/bin/sh
#	Recursive grep
#	$Id: rgrep,v 1.3 1999-03-17 23:21:58 steve Exp $


find . '(' -name '*.java' -o -name '*html' -o -name '*.xh' -o -name '*.ts' \
	-o -name '*.tex' -o -name '*make*' \
        -o -name '*.p[lm]' -o -name '*.inc' -o -name '*akefile' ')' -type f  \
	\! -path '*JavaDoc*' \
    -exec grep $* {} /dev/null \;
