#!/bin/sh
#	Recursive grep
#	$Id: rgrep,v 1.2 1999-03-12 19:23:54 steve Exp $


find . '(' -name '*.java' -o -name '*.html' -o -name '*.xh' -o -name '*.ts' \
	-o -name '*.tex' -o -name '*make*' \
        -o -name '*.p[lm]' -o -name '*.inc' -o -name '*akefile' ')' -type f  \
	\! -path '*JavaDoc*' \
    -exec grep $* {} /dev/null \;
