#!/bin/sh
#	Display linecounts under "." using xdu.
#	$Id: x-lc,v 1.2 1999-03-12 19:23:55 steve Exp $

find ${*-.} -type f ! -name '*~' ! -name '#*' ! -name '.#*' \
    ! -name '*.class' ! -name '*.o' ! -name '*.log' ! -name '*.zip' \
    -exec wc -l {} \; \
    | xdu -c 4 -name "Line Counts: $*" -geom +105+80
