###### org/risource/Makefile:	RiSource.org's Java classes.
#	$Id: Makefile,v 1.5 1999-09-09 22:27:21 steve Exp $

############################################################################### 
 # The contents of this file are subject to the Ricoh Source Code Public
 # License Version 1.0 (the "License"); you may not use this file except in
 # compliance with the License.  You may obtain a copy of the License at
 # http://www.risource.org/RPL
 #
 # Software distributed under the License is distributed on an "AS IS" basis,
 # WITHOUT WARRANTY OF ANY KIND, either express or implied.  See the License
 # for the specific language governing rights and limitations under the
 # License.
 #
 # This code was initially developed by Ricoh Silicon Valley, Inc.  Portions
 # created by Ricoh Silicon Valley, Inc. are Copyright (C) 1995-1999.  All
 # Rights Reserved.
 #
 # Contributor(s):
 #
############################################################################## 


PACKAGE="org.risource"
TOPDIR=../..

### These are the packages to be built.  
###	Only the top-level directories are needed; 
###	make descends into each one recursively.

PACKAGES = \
	ds \
	util \
	dom \
	dps \
	site \
	content \
	tf \
	pia

FILES = Version.java

include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make














