### Makefile for Doc/Notes/steve/Design
#	$Id: Makefile,v 1.1 1999-04-13 18:30:52 steve Exp $	
# 	COPYRIGHT 1998, Ricoh Silicon Valley

PIADIR=../../../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Design
MYPATH=Doc/Notes/steve/Design
include $(MF_DIR)/file.make
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make

