### Makefile for Doc/Notes/steve/Design
#	$Id: Makefile,v 1.2 2001-01-11 23:36:53 steve Exp $	

PIADIR=../../../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Design
MYPATH=Doc/Notes/steve/Design
include $(MF_DIR)/file.make
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make

