###### org/w3c/Makefile:	World Wide Web Consortium
# 	$Id: Makefile,v 1.2 1999-03-12 19:31:13 steve Exp $

PACKAGE=org.w3c
TOPDIR=../..

PACKAGES = \
	dom

include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make
