###### org/w3c/Makefile:	World Wide Web Consortium
# 	$Id: Makefile,v 1.3 1999-03-12 19:50:04 pgage Exp $

PACKAGE=org.w3c
TOPDIR=../..

PACKAGES = \
	dom \
	tools \
	util \
	www

include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make
