###### org/w3c/Makefile:	World Wide Web Consortium
# 	Makefile,v 1.2 1999/03/02 00:46:28 pgage Exp

PACKAGE=org.w3c
TOPDIR=../..

PACKAGES = \
	dom

include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make
