######  JP/ac/osaka_u/ender/Makefile:	created to compile the regex package
# 	

PACKAGE=JP.ac.osaka_u.ender
TOPDIR=../../../..

PACKAGES = \
	util

include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make
