######  Makefile: 
#	for the Jigsaw org.w3c.tools.timers package

PACKAGE=org.w3c.tools.timers
TOPDIR=../../../..

FILES = \
	EventHandler.java \
	EventManager.java \
	DateThread.java

include $(TOPDIR)/makefiles/file.make


