######  Makefile: 
#	for a subset of Jigsaw org.w3c.www.http package


PACKAGE = "org.w3c.www.http"
TOPDIR=../../../..

FILES = \
	HTTP.java \
	BasicValue.java \
	CookieDate.java \
	HeaderDescription.java \
	HeaderValue.java \
	HttpAccessException.java \
	HttpBuffer.java \
	HttpCacheControl.java \
	HttpDate.java \
	HttpEntityMessage.java \
	HttpEntityTag.java \
	HttpEntityTagList.java \
	HttpInteger.java \
	HttpMessage.java \
	HttpMimeType.java \
	HttpParser.java \
	HttpParserException.java \
	HttpContentRange.java \
	HttpReplyMessage.java \
	HttpRequestMessage.java \
	HttpString.java \
	HttpTokenList.java \
	HttpCaseTokenList.java \
	HttpUpperTokenList.java \
	MimeParserMessageFactory.java \
	MimeParserReplyFactory.java \
	MimeParserRequestFactory.java \
	HttpWarning.java \
	HttpWarningList.java \
	HttpAccept.java \
	HttpAcceptList.java \
	HttpAcceptLanguage.java \
	HttpAcceptLanguageList.java \
	HttpAcceptCharset.java \
	HttpAcceptCharsetList.java \
	HttpAcceptEncoding.java \
	HttpAcceptEncodingList.java \
	HttpRange.java \
	HttpRangeList.java \
	HttpCredential.java \
	HttpChallenge.java \
	HttpBag.java \
	ParseState.java \
	HttpSetCookieList.java \
	headerEnumerator.java \
	HttpFactory.java \
	HttpInvalidValueException.java


include $(TOPDIR)/makefiles/file.make
#include $(TOPDIR)/makefiles/package.make


