###### org/xml/sax/Makefile:	Simple API for XML
# 	$Id: Makefile,v 1.1 1999-07-12 22:45:35 steve Exp $


PACKAGE=org.xml.sax
TOPDIR=../../..

FILES = $(wildcard *.java)

# include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make

