###### org/xml/sax/Makefile:	Simple API for XML
# 	$Id: Makefile,v 1.2 2000-01-12 01:53:19 steve Exp $


PACKAGE=org.xml.sax
TOPDIR=../../..

FILES =  \
	AttributeList.java \
	DTDHandler.java \
	DemoHandler.java \
	DocumentHandler.java \
	EntityResolver.java \
	ErrorHandler.java \
	HandlerBase.java \
	InputSource.java \
	Locator.java \
	Parser.java \
	SAXException.java \
	SAXParseException.java \

DEMOS= \
	ByteStreamDemo.java \
	CharacterStreamDemo.java \
	EntityDemo.java \
	SystemIdDemo.java


PACKAGES = \
	helpers

include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make

