<h2>About the localFile Agent</h2> <!-- -*-html-helper-*- -->
<!-- Copyright 1997 Ricoh Silicon Valley -->

The localFile Agent puts banners on top of pages that come from local files
served by the PIA (in other words, from DOFS agents).
This is indicated by the PIA logo (<img src="/Icon/pia24.gif" height=24
width=43>) at the front of the banner, which is a link to the PIA's home page.
<p>

<inc-footer cvsid="about.inc,v 1.1 1999/02/05 21:22:16 steve Exp">
