<h2>About the fileTools Agent</h2> <!-- -*-html-helper-*- -->
<!-- Copyright 1997 Ricoh Innovations, Inc. -->

The fileTools Agent puts banners on top of pages that come from local files
served by the PIA (in other words, from DOFS agents).
This is indicated by the PIA logo (<img src="&PIA:rootPath;Icon/pia24.png" height=24
width=43>) at the front of the banner, which is a link to the PIA's home page.
<p>

<inc-footer cvsid="$Id: about.inc,v 1.9 2001-01-11 23:36:31 steve Exp $">
