###### pia/Makefile:	Platform for Information Appliances
#	Makefile,v 1.18 1999/03/02 00:46:11 pgage Exp

############################################################################### 
 # The contents of this file are subject to the Ricoh Source Code Public
 # License Version 1.0 (the "License"); you may not use this file except in
 # compliance with the License.  You may obtain a copy of the License at
 # http://www.risource.org/RPL
 #
 # Software distributed under the License is distributed on an "AS IS" basis,
 # WITHOUT WARRANTY OF ANY KIND, either express or implied.  See the License
 # for the specific language governing rights and limitations under the
 # License.
 #
 # This code was initially developed by Ricoh Silicon Valley, Inc.  Portions
 # created by Ricoh Silicon Valley, Inc. are Copyright (C) 1995-1999.  All
 # Rights Reserved.
 #
 # Contributor(s):
 #
############################################################################## 


PACKAGE=crc.dom
TOPDIR=../..

PACKAGES =

INTERFACES = \
	Attribute.java \
	AttributeList.java \
	Comment.java \
	Declaration.java \
	Document.java \
	DocumentContext.java \
	Element.java \
	EditableNodeList.java \
	NamedNodeList.java \
	Node.java \
	NodeList.java \
	PI.java \
	Text.java \
	CDATASection.java \
	Notation.java \
	Entity.java 

EXCEPTIONS = \
	NoSuchNodeException.java \
	NotMyChildException.java 

# All of the following appear to be unused in the DPS

OTHER_INTERFACES = \
	DOMFactory.java 

OTHER_CLASSES = \
	NodeType.java 

ENUMERATORS = \
	LinkedNodeListEnumerator.java \
	NodeEnumerator.java \
	ArrayNodeListEnumerator.java \
	ChildNodeListEnumerator.java 

LIST_CLASSES = \
	LinkedList.java \
	LinkedNodeList.java \
	ArrayNodeList.java \
	AttrList.java 

NODE_CLASSES = \
	AbstractDOMFactory.java \
	AbstractDocument.java  \
	AbstractEntity.java \
	AbstractNamedList.java \
	AbstractNode.java  \
	AgentEntity.java \
	AttributeDefinition.java \
	BasicAttribute.java \
	BasicComment.java \
	BasicDOMFactory.java \
	BasicDocument.java \
	BasicElement.java \
	BasicNamedNode.java \
	BasicNamedNodeList.java \
	BasicPI.java \
	BasicText.java \
	CRCAttribute.java \
	CRCDOM.java \
	CRCDOMFactory.java \
	CRCDocument.java \
	CRCElement.java \
	ChildNodeList.java \
	ConnectionType.java \
	ContentType.java \
	DOM.java \
	DeclaredValueType.java \
	DefaultValueType.java \
	DocumentType.java \
	ElementDefinition.java \
	ElementToken.java \
	ExternalEntity.java \
	ExternalNDATAEntity.java \
	ExternalTextEntity.java \
	InternalEntity.java \
	LocalEntity.java \
	Logger.java \
	ModelGroup.java \
	NdataEntity.java \
	NodeWrapper.java \
	NotMyChildException.java \
	OccurrenceType.java \
	PCDATAToken.java \
	Report.java \
	SystemEntity.java \
	TextEntity.java

FILES = $(INTERFACES) $(EXCEPTIONS)

include $(TOPDIR)/makefiles/file.make
#include $(TOPDIR)/makefiles/package.make

### Dependencies:
