<!-- This heading is meant to be included using read. -*-html-helper-*- -->
<!-- Copyright 1997 Ricoh Silicon Valley -->
<table cellspacing=0 cellpadding=0 border=0>
<tr nowrap nobr><th align=left width=170 valign=bottom nowrap><a
	href="http://rsv.ricoh.com/"><img src="/Agency/Icons/ricoh.png"
	border=0 width=170 height=48 alt="R I C O H"></a></th>
    <th width=170 nowrap></th>
    <th align=left nowrap nobr valign=center width=170>
        <a href="/"><img width=85 height=45 border=0
	    	         src="/Agency/Icons/pia45.png" alt=PIA></a></th></tr>
<tr height=2><td colspan=3  nowrap nobr
    ><img src="/Agency/Icons/rule.png" height=6 width=469></td></tr>
<!--img src="/Agency/Icons/blackline425.png" height=2 width=425-->
<tr nowrap nobr><th align=left valign=top><a href="http://rsv.ricoh.com/"><img
	src="/Agency/Icons/ricoh-silicon-valley.png" alt="RICOH SILICON VALLEY"
	border=0 width=170 height=21></a></th>
    <th align=right valign=top width=170><a
	href="/&agentName;">&agentName;</a>: </th>
    <th align=left colspan=2><if><get entity name=title />
	<then><get entity name=title /></then>
	<else>&fileName;</else></if></th></tr>
</table>
<!-- $Id: heading.inc,v 1.2 1999-11-05 01:12:42 steve Exp $ -->
