###### Makefile: for subset of Jigsaw www packages
#

PACKAGE="org.w3c.www"
TOPDIR=../../..

PACKAGES = \
	http \
	mime

include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make
