### Makefile for /Agents
#	$Id: Makefile,v 1.1 1999-10-14 18:04:14 steve Exp $	
# 	COPYRIGHT 1999, Ricoh Silicon Valley

PIADIR=../.
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Agents
MYPATH=Agents

### This Makefile exists in case any files need to be built in subdirectories.
###	The original idea was to strip documentation from local tagsets
###	in hopes of achieving a speedup; that turns out not to be a major
###	improvement in most cases.  
###
### 	Nevertheless, some applications may eventually benefit from offline
###	processing.

#SUBDIRS=SimpleCalendar

include $(MF_DIR)/file.make
#include $(MF_DIR)/subdir.make

