### Makefile for /Apps
#	$Id: Makefile,v 1.1 2000-05-26 22:59:05 steve Exp $
# 	COPYRIGHT 2000, RiSource.org

PIADIR=../.
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Apps
MYPATH=/Apps
include $(MF_DIR)/file.make
include $(MF_DIR)/subdir.make

