###### org/Makefile:	Imported organizations' Java classes
#	Makefile,v 1.2 1999/03/02 00:46:27 pgage Exp


PACKAGE="org"
TOPDIR=..

### These are the packages to be built.  
###	Only the top-level directories are needed; 
###	make descends into each one recursively.

PACKAGES = \
	w3c

include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make














