######  JP/ac/osaka_u/ender/util/regex/Makefile:
#	created to compile the regex package


PACKAGE=JP.ac.osaka_u.ender.util.regex
TOPDIR=../../../../../..

FILES = \
	RTree.java \
	Chars.java \
	RegExp.java \
	DList.java \
	RegExpCore.java \
	DSList.java \
	RegExpDFA.java \
	DState.java \
	RegExpDebug.java \
	MatchInfo.java \
	RegExpNFA.java \
	NFABuildException.java \
	RegExpParser.java \
	NList.java \
	RegExpSyntaxException.java

include $(TOPDIR)/makefiles/file.make





