### Makefile for Doc/Notes/steve/Archive
#	$Id: Makefile,v 1.2 2001-01-11 23:36:52 steve Exp $	

PIADIR=../../../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Archive
MYPATH=Doc/Notes/steve/Archive
include $(MF_DIR)/file.make
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make

