### Makefile for Doc/Notes/steve/Archive
#	$Id: Makefile,v 1.1 1999-07-21 20:49:01 steve Exp $	
# 	COPYRIGHT 1998, Ricoh Silicon Valley

PIADIR=../../../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Archive
MYPATH=Doc/Notes/steve/Archive
include $(MF_DIR)/file.make
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make

