###### org/w3c/dom/Makefile:	Document Object Model
# 	Makefile,v 1.3 1999/03/02 00:46:28 pgage Exp


PACKAGE=org.w3c.dom
TOPDIR=../../..

FILES = $(wildcard *.java)

# Note that at the moment we are not building the HTML classes,
# since we don't use them. 

# include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make

