###### org/w3c/dom/Makefile:	Document Object Model
# 	$Id: Makefile,v 1.2 1999-03-12 19:31:14 steve Exp $


PACKAGE=org.w3c.dom
TOPDIR=../../..

FILES = $(wildcard *.java)

# Note that at the moment we are not building the HTML classes,
# since we don't use them. 

# include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make

