###### dps/active/Makefile:	DOM implementation classes
# 	$Id: Makefile,v 1.4 1999-04-07 23:21:01 steve Exp $

############################################################################### 
 # The contents of this file are subject to the Ricoh Source Code Public
 # License Version 1.0 (the "License"); you may not use this file except in
 # compliance with the License.  You may obtain a copy of the License at
 # http://www.risource.org/RPL
 #
 # Software distributed under the License is distributed on an "AS IS" basis,
 # WITHOUT WARRANTY OF ANY KIND, either express or implied.  See the License
 # for the specific language governing rights and limitations under the
 # License.
 #
 # This code was initially developed by Ricoh Silicon Valley, Inc.  Portions
 # created by Ricoh Silicon Valley, Inc. are Copyright (C) 1995-1999.  All
 # Rights Reserved.
 #
 # Contributor(s):
 #
############################################################################## 


PACKAGE=org.risource.dps.active
TOPDIR=../../../..

INTERFACES = \
	ActiveNode.java \
	ActiveNodeList.java \
	ActiveNodeMap.java \
	ActiveAttrList.java \
	ActiveValue.java \
	ActiveAttr.java \
	ActiveCharData.java \
	ActiveComment.java \
	ActiveDecl.java \
	ActiveDocument.java \
	ActiveDocType.java \
	ActiveElement.java \
	ActiveEntity.java \
	ActiveEntityRef.java \
	ActivePI.java \
	ActiveText.java

EXCEPTIONS = \
	DPSException.java 

CLASSES = \
	NodeType.java

FILES = $(INTERFACES) $(EXCEPTIONS) $(CLASSES)

include $(TOPDIR)/makefiles/file.make

### Dependencies
