######  Makefile: 
#	for the Jigsaw org.w3c.www.mime package

PACKAGE=org.w3c.www.mime
TOPDIR= ../../../..

FILES = \
	MimeHeaderHolder.java \
	MimeParser.java \
	MimeParserException.java \
	MimeParserFactory.java \
	MimeType.java \
	MimeTypeFormatException.java \
	MultipartInputStream.java \
	MimeHeaders.java \
	MimeHeadersFactory.java \
	Utils.java


include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make

